#include "dialecttests.h"

static QiModelMetaInfo *model1Info() { return qiMetaInfo<Model1>(); }

void DialectTests::factory() {
    QScopedPointer<QiSqlStatement> lite(QiSqlStatement::forDriver("QSQLITE"));
    QScopedPointer<QiSqlStatement> my(QiSqlStatement::forDriver("QMYSQL"));
    QScopedPointer<QiSqlStatement> maria(QiSqlStatement::forDriver("QMARIADB"));
    QScopedPointer<QiSqlStatement> pg(QiSqlStatement::forDriver("QPSQL"));
    QScopedPointer<QiSqlStatement> unknown(QiSqlStatement::forDriver("QODBC"));

    QCOMPARE(lite->driverName(),  QString("SQLITE"));
    QCOMPARE(my->driverName(),    QString("MYSQL"));
    QCOMPARE(maria->driverName(), QString("MYSQL"));   // MariaDB shares the MySQL generator
    QCOMPARE(pg->driverName(),    QString("PSQL"));
    QCOMPARE(unknown->driverName(), QString("SQLITE")); // unknown driver -> SQLite fallback
}

void DialectTests::columnTypes() {
    QiSqliteStatement lite;
    QiMysqlStatement  my;
    QiPgStatement     pg;

    // integers
    QCOMPARE(lite.columnTypeName(QMetaType::Int), QString("INTEGER"));
    QCOMPARE(my.columnTypeName(QMetaType::Int),   QString("INT"));
    QCOMPARE(pg.columnTypeName(QMetaType::Int),   QString("INTEGER"));

    // strings
    QCOMPARE(lite.columnTypeName(QMetaType::QString), QString("TEXT"));
    QCOMPARE(my.columnTypeName(QMetaType::QString),   QString("VARCHAR(255)"));
    QCOMPARE(pg.columnTypeName(QMetaType::QString),   QString("TEXT"));

    // bool + blob
    QCOMPARE(my.columnTypeName(QMetaType::Bool),      QString("TINYINT(1)"));
    QCOMPARE(pg.columnTypeName(QMetaType::Bool),      QString("BOOLEAN"));
    QCOMPARE(pg.columnTypeName(QMetaType::QByteArray),QString("BYTEA"));
}

void DialectTests::mysqlStringTyping() {
    QiMysqlStatement my;
    QiClause plain;                        // no flags
    QiClause pk(QiClause::PRIMARY_KEY);
    QiClause uniq(QiClause::UNIQUE);

    // Plain text must not truncate -> TEXT.
    QCOMPARE(my.columnTypeForField(QMetaType::QString, plain), QString("TEXT"));
    // A keyed / unique string must be indexable -> bounded VARCHAR.
    QCOMPARE(my.columnTypeForField(QMetaType::QString, pk),   QString("VARCHAR(255)"));
    QCOMPARE(my.columnTypeForField(QMetaType::QString, uniq), QString("VARCHAR(255)"));
    // Non-string types are unaffected by the clause.
    QCOMPARE(my.columnTypeForField(QMetaType::Int, plain),    QString("INT"));
}

void DialectTests::extraTypes() {
    QiSqliteStatement lite;
    QiMysqlStatement  my;
    QiPgStatement     pg;

    // float (single precision)
    QCOMPARE(my.columnTypeName(QMetaType::Float), QString("FLOAT"));
    QCOMPARE(pg.columnTypeName(QMetaType::Float), QString("REAL"));
    QVERIFY(!lite.columnTypeName(QMetaType::Float).isNull());

    // time
    QCOMPARE(my.columnTypeName(QMetaType::QTime),   QString("TIME"));
    QCOMPARE(pg.columnTypeName(QMetaType::QTime),   QString("TIME"));
    QCOMPARE(lite.columnTypeName(QMetaType::QTime), QString("TIME"));

    // JSON is stored as TEXT on every backend (portable + parameter-safe round-trip)
    QCOMPARE(lite.columnTypeName(QMetaType::QJsonObject), QString("TEXT"));
    QCOMPARE(my.columnTypeName(QMetaType::QJsonObject),   QString("TEXT"));
    QCOMPARE(pg.columnTypeName(QMetaType::QJsonObject),   QString("TEXT"));
}

void DialectTests::primaryKey() {
    QiMysqlStatement my;
    QiPgStatement    pg;

    QCOMPARE(my.primaryKeyClause("INT"),         QString("AUTO_INCREMENT PRIMARY KEY"));
    QCOMPARE(my.primaryKeyClause("VARCHAR(255)"),QString("PRIMARY KEY"));   // no auto-inc on text

    QVERIFY(pg.primaryKeyClause("INTEGER").contains("GENERATED BY DEFAULT AS IDENTITY"));
    QCOMPARE(pg.primaryKeyClause("TEXT"),        QString("PRIMARY KEY"));
}

void DialectTests::createTable() {
    QiModelMetaInfo *info = model1Info();
    QiSqliteStatement lite;
    QiMysqlStatement  my;
    QiPgStatement     pg;

    const QString liteS = lite.createTableIfNotExists(info);
    QVERIFY(liteS.contains("CREATE TABLE IF NOT EXISTS model1"));
    QVERIFY(liteS.contains("AUTOINCREMENT"));

    const QString myS = my.createTableIfNotExists(info);
    QVERIFY(myS.contains("CREATE TABLE IF NOT EXISTS model1"));
    QVERIFY(myS.contains("AUTO_INCREMENT PRIMARY KEY"));
    QVERIFY(myS.contains("ENGINE=InnoDB"));
    QVERIFY(myS.contains("TEXT"));              // plain (non-key) strings are TEXT, not truncated

    const QString pgS = pg.createTableIfNotExists(info);
    QVERIFY(pgS.contains("CREATE TABLE IF NOT EXISTS model1"));
    QVERIFY(pgS.contains("GENERATED BY DEFAULT AS IDENTITY"));
    QVERIFY(pgS.contains("TEXT"));
}

void DialectTests::upsert() {
    QiModelMetaInfo *info = model1Info();
    const QStringList fields   = QStringList() << "id" << "key" << "value";
    const QStringList conflict = QStringList() << "key";

    QiSqliteStatement lite;
    QiMysqlStatement  my;
    QiPgStatement     pg;

    const QString myS = my.upsertInto(info, fields, conflict);
    QVERIFY(myS.contains("ON DUPLICATE KEY UPDATE"));
    QVERIFY(myS.contains("value=VALUES(value)"));

    const QString pgS = pg.upsertInto(info, fields, conflict);
    QVERIFY(pgS.contains("ON CONFLICT(key)"));
    QVERIFY(pgS.contains("value=excluded.value"));

    const QString liteS = lite.upsertInto(info, fields, conflict);
    QVERIFY(liteS.contains("ON CONFLICT(key)"));
}

void DialectTests::pgReturning() {
    QiPgStatement     pg;
    QiSqliteStatement lite;
    QiMysqlStatement  my;

    // Postgres fetches the new id with a follow-up query; SQLite/MySQL use lastInsertId().
    QCOMPARE(pg.lastInsertIdQuery(), QString("SELECT lastval()"));
    QVERIFY(lite.lastInsertIdQuery().isEmpty());
    QVERIFY(my.lastInsertIdQuery().isEmpty());
}

void DialectTests::tableExists() {
    QiModelMetaInfo *info = model1Info();
    QiSqliteStatement lite;
    QiMysqlStatement  my;
    QiPgStatement     pg;

    QVERIFY(lite.exists(info).contains("sqlite_master"));
    QVERIFY(my.exists(info).contains("information_schema"));
    QVERIFY(pg.exists(info).contains("information_schema"));
}
