#!/usr/bin/env python3
"""Generate a single-header, header-only build of Qivot's core ORM.

Reads the real src/*.h and src/*.cpp and emits single_include/qivot.hpp:

  * the declarations (all core headers, in dependency order) are always visible;
  * the implementations (the .cpp bodies) are compiled only where the consumer
    writes `#define QIVOT_IMPLEMENTATION` before including the header — the
    stb-style pattern, so there is no separate library to build or link.

Re-run this whenever src/ changes:  python3 tools/amalgamate.py

The two Q_OBJECT classes (QiJsonRequest / QiListModel) are intentionally
excluded: a Q_OBJECT type needs moc-generated code, which cannot be header-only.
They remain available through the normal compiled build (QIVOT_WITH_NETWORK / QML).
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "src"))
OUT_DIR = os.path.normpath(os.path.join(HERE, "..", "dist"))
OUT = os.path.join(OUT_DIR, "qivot.hpp")

# Q_OBJECT (moc) units and the umbrella header are excluded from the amalgamation.
# qiasync.h is also excluded: it depends on QtConcurrent, which the lean
# header-only core must not force on every consumer (use the compiled build).
EXCLUDE_HEADERS = {"qilistmodel.h", "qijsonrequest.h", "qivot.h", "qiasync.h"}
EXCLUDE_CPP = {"qilistmodel.cpp", "qijsonrequest.cpp"}

INTERNAL_INCLUDE = re.compile(r'^\s*#\s*include\s*[<"]qi[a-zA-Z0-9_]+\.h[>"]\s*$')


def strip_internal_includes(text):
    """Drop `#include <qiX.h>` / "qiX.h" lines; the content is inlined instead.
    Everything else (Qt includes, include guards) is kept verbatim."""
    return "".join(l for l in text.splitlines(keepends=True)
                   if not INTERNAL_INCLUDE.match(l))


def internal_deps(text, header_set):
    deps = []
    for m in re.finditer(r'#\s*include\s*[<"](qi[a-zA-Z0-9_]+\.h)[>"]', text):
        h = m.group(1)
        if h in header_set and h not in deps:
            deps.append(h)
    return deps


def topo_sort(headers, deps_map):
    """Kahn-ish DFS topo sort so a header is emitted after everything it needs."""
    order, temp, done = [], set(), set()

    def visit(h, stack):
        if h in done:
            return
        if h in temp:
            raise RuntimeError("include cycle: " + " -> ".join(stack + [h]))
        temp.add(h)
        for d in deps_map.get(h, []):
            visit(d, stack + [h])
        temp.discard(h)
        done.add(h)
        order.append(h)

    for h in sorted(headers):
        visit(h, [])
    return order


def read(name):
    with open(os.path.join(SRC, name), "r") as f:
        return f.read()


def main():
    all_h = [f for f in os.listdir(SRC) if f.endswith(".h")]
    # Public headers to amalgamate: exclude moc units, umbrella, and privates.
    pub_headers = {f for f in all_h
                   if f not in EXCLUDE_HEADERS and not f.endswith("_p.h")}
    priv_headers = sorted(f for f in all_h if f.endswith("_p.h"))

    deps = {h: internal_deps(read(h), pub_headers) for h in pub_headers}
    header_order = topo_sort(pub_headers, deps)

    cpps = sorted(f for f in os.listdir(SRC)
                  if f.endswith(".cpp") and f not in EXCLUDE_CPP)

    # Concatenating .cpp into one TU means file-scope `static` names must be
    # globally unique. Fail loudly if two units share one, so a future edit
    # can't silently break the generated header.
    static_def = re.compile(r'^\s*static\b[^;{()=]*?([A-Za-z_]\w*)\s*[=;({]', re.M)
    owners = {}
    clashes = []
    for c in cpps:
        for name in set(static_def.findall(read(c))):
            if name in owners:
                clashes.append("  '%s' in %s and %s" % (name, owners[name], c))
            else:
                owners[name] = c
    if clashes:
        raise SystemExit("amalgamate: duplicate file-scope static name(s) — "
                         "rename them uniquely in src/:\n" + "\n".join(clashes))

    parts = []
    parts.append("// =====================================================================\n")
    parts.append("//  Qivot - single-header, header-only core ORM\n")
    parts.append("//  GENERATED by tools/amalgamate.py - DO NOT EDIT BY HAND.\n")
    parts.append("//  Re-generate with:  python3 tools/amalgamate.py\n")
    parts.append("//\n")
    parts.append("//  Usage: #include <qivot.hpp> everywhere; in exactly ONE .cpp add\n")
    parts.append("//         #define QIVOT_IMPLEMENTATION\n")
    parts.append("//         #include <qivot.hpp>\n")
    parts.append("// =====================================================================\n")
    parts.append("#ifndef QIVOT_HPP\n#define QIVOT_HPP\n\n")

    for h in header_order:
        parts.append("\n// ---- src/%s %s\n" % (h, "-" * max(2, 56 - len(h))))
        parts.append(strip_internal_includes(read(h)))

    parts.append("\n#endif // QIVOT_HPP\n")

    # ---- implementation section (compiled in one TU) ----
    parts.append("\n#ifdef QIVOT_IMPLEMENTATION\n")
    parts.append("#ifndef QIVOT_IMPLEMENTATION_INCLUDED\n")
    parts.append("#define QIVOT_IMPLEMENTATION_INCLUDED\n")
    for h in priv_headers:
        parts.append("\n// ---- src/%s (private) %s\n" % (h, "-" * 8))
        parts.append(strip_internal_includes(read(h)))
    for c in cpps:
        parts.append("\n// ---- src/%s %s\n" % (c, "-" * max(2, 56 - len(c))))
        parts.append(strip_internal_includes(read(c)))
    parts.append("\n#endif // QIVOT_IMPLEMENTATION_INCLUDED\n")
    parts.append("#endif // QIVOT_IMPLEMENTATION\n")

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w") as f:
        f.write("".join(parts))

    print("wrote %s" % OUT)
    print("  headers: %d   impl units: %d   private: %d"
          % (len(header_order), len(cpps), len(priv_headers)))
    print("  header order: %s" % " ".join(h[:-2] for h in header_order))


if __name__ == "__main__":
    sys.exit(main())
