-- GitLab Database Schema (PostgreSQL)
-- Git repository management, CI/CD, and project collaboration platform

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    encrypted_password VARCHAR NOT NULL,
    reset_password_token VARCHAR,
    reset_password_sent_at TIMESTAMP,
    remember_created_at TIMESTAMP,
    sign_in_count INTEGER DEFAULT 0,
    current_sign_in_at TIMESTAMP,
    last_sign_in_at TIMESTAMP,
    current_sign_in_ip INET,
    last_sign_in_ip INET,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name VARCHAR,
    admin BOOLEAN DEFAULT FALSE,
    projects_limit INTEGER,
    skype VARCHAR,
    linkedin VARCHAR,
    twitter VARCHAR,
    username VARCHAR NOT NULL UNIQUE,
    type VARCHAR DEFAULT 'User',
    state VARCHAR DEFAULT 'active',
    confirmed_at TIMESTAMP,
    confirmation_token VARCHAR,
    confirmation_sent_at TIMESTAMP,
    locked_at TIMESTAMP,
    description TEXT,
    encrypted_otp_secret VARCHAR,
    encrypted_otp_secret_iv VARCHAR,
    otp_required_for_login BOOLEAN DEFAULT FALSE,
    last_activity_on DATE,
    avatar VARCHAR,
    public_email VARCHAR,
    organization_id BIGINT,
    ghost BOOLEAN DEFAULT FALSE,
    INDEX idx_username (username),
    INDEX idx_state (state)
);

CREATE TABLE namespaces (
    id BIGINT PRIMARY KEY,
    name VARCHAR NOT NULL,
    path VARCHAR NOT NULL,
    owner_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    type VARCHAR DEFAULT 'User',
    description VARCHAR,
    avatar VARCHAR,
    organization_id BIGINT,
    state SMALLINT DEFAULT 0,
    INDEX idx_owner_id (owner_id),
    INDEX idx_path (path),
    UNIQUE INDEX idx_namespace_path (owner_id, path),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE projects (
    id BIGINT PRIMARY KEY,
    name VARCHAR,
    name_with_namespace VARCHAR,
    path VARCHAR,
    path_with_namespace VARCHAR,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    creator_id BIGINT,
    description TEXT,
    default_branch VARCHAR DEFAULT 'master',
    tag_list TEXT[],
    archived BOOLEAN DEFAULT FALSE,
    visibility_level INTEGER DEFAULT 0,
    issues_enabled BOOLEAN DEFAULT TRUE,
    merge_requests_enabled BOOLEAN DEFAULT TRUE,
    wiki_enabled BOOLEAN DEFAULT TRUE,
    jobs_enabled BOOLEAN DEFAULT TRUE,
    snippets_enabled BOOLEAN DEFAULT TRUE,
    container_registry_enabled BOOLEAN DEFAULT TRUE,
    last_activity_at TIMESTAMP,
    namespace_id BIGINT NOT NULL,
    import_type VARCHAR,
    import_source VARCHAR,
    ci_config_path VARCHAR,
    shared_runners_enabled BOOLEAN DEFAULT TRUE,
    lfs_enabled BOOLEAN DEFAULT TRUE,
    avatar VARCHAR,
    repository_storage VARCHAR,
    organization_id BIGINT,
    mirror BOOLEAN DEFAULT FALSE,
    star_count INTEGER DEFAULT 0,
    forks_count INTEGER DEFAULT 0,
    issues_count INTEGER DEFAULT 0,
    merge_requests_count INTEGER DEFAULT 0,
    notes_count INTEGER DEFAULT 0,
    wiki_page_count INTEGER DEFAULT 0,
    INDEX idx_namespace_id (namespace_id),
    INDEX idx_creator_id (creator_id),
    UNIQUE INDEX idx_path_namespace (path, namespace_id),
    FOREIGN KEY (namespace_id) REFERENCES namespaces(id),
    FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE project_members (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    access_level INTEGER NOT NULL,
    type VARCHAR,
    notification_level INTEGER DEFAULT 3,
    created_by_id BIGINT,
    expires_at DATE,
    state VARCHAR,
    INDEX idx_user_id (user_id),
    INDEX idx_project_id (project_id),
    UNIQUE INDEX idx_project_user (project_id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE issues (
    id BIGINT PRIMARY KEY,
    title VARCHAR NOT NULL,
    description TEXT,
    project_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    author_id BIGINT NOT NULL,
    assignee_ids BIGINT[],
    state VARCHAR DEFAULT 'opened',
    state_id INTEGER,
    iid BIGINT,
    closed_by_id BIGINT,
    closed_at TIMESTAMP,
    due_date DATE,
    milestone_id BIGINT,
    weight INTEGER,
    confidential BOOLEAN DEFAULT FALSE,
    created_by_id BIGINT,
    updated_by_id BIGINT,
    last_edited_at TIMESTAMP,
    last_edited_by_id BIGINT,
    relative_position INTEGER,
    start_date DATE,
    discussion_locked BOOLEAN,
    time_estimate INTEGER,
    total_time_spent INTEGER,
    time_change INTEGER,
    escalation_status VARCHAR,
    escalation_policy_id BIGINT,
    INDEX idx_project_id (project_id),
    INDEX idx_author_id (author_id),
    INDEX idx_state (state),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE TABLE merge_requests (
    id BIGINT PRIMARY KEY,
    target_branch VARCHAR NOT NULL,
    source_branch VARCHAR NOT NULL,
    project_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    state VARCHAR DEFAULT 'opened',
    state_id INTEGER,
    iid BIGINT,
    title VARCHAR,
    description TEXT,
    assignee_ids BIGINT[],
    reviewer_ids BIGINT[],
    source_project_id BIGINT,
    target_project_id BIGINT,
    merge_user_id BIGINT,
    merged_at TIMESTAMP,
    closed_by_id BIGINT,
    closed_at TIMESTAMP,
    created_by_id BIGINT,
    updated_by_id BIGINT,
    merge_commit_sha VARCHAR,
    merge_when_pipeline_succeeds BOOLEAN DEFAULT FALSE,
    deleted_by_id BIGINT,
    in_progress_merge_commit_sha VARCHAR,
    lock_version INTEGER,
    time_estimate INTEGER,
    total_time_spent INTEGER,
    latest_merge_request_diff_id BIGINT,
    allow_collaboration BOOLEAN,
    require_squash BOOLEAN DEFAULT FALSE,
    squash_commit_sha VARCHAR,
    discussion_locked BOOLEAN,
    external_author VARCHAR,
    source_branch_sha VARCHAR,
    target_branch_sha VARCHAR,
    merge_ongoing BOOLEAN DEFAULT FALSE,
    INDEX idx_project_id (project_id),
    INDEX idx_author_id (author_id),
    INDEX idx_state (state),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id),
    FOREIGN KEY (source_project_id) REFERENCES projects(id)
);

CREATE TABLE notes (
    id BIGINT PRIMARY KEY,
    noteable_type VARCHAR,
    noteable_id BIGINT,
    project_id BIGINT,
    author_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    note TEXT,
    note_html TEXT,
    is_award BOOLEAN DEFAULT FALSE,
    award VARCHAR,
    cached_markdown_version INTEGER,
    discussion_id VARCHAR,
    resolved_by_id BIGINT,
    resolved_at TIMESTAMP,
    system BOOLEAN DEFAULT FALSE,
    internal BOOLEAN DEFAULT FALSE,
    INDEX idx_noteable (noteable_type, noteable_id),
    INDEX idx_project_id (project_id),
    INDEX idx_author_id (author_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE TABLE ci_pipelines (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    status VARCHAR DEFAULT 'created',
    config JSONB,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    committed_at TIMESTAMP,
    duration INTEGER,
    user_id BIGINT,
    iid BIGINT,
    ref VARCHAR,
    sha VARCHAR,
    before_sha VARCHAR,
    source VARCHAR,
    tag BOOLEAN DEFAULT FALSE,
    yaml_errors TEXT,
    manual_actions_blocked BOOLEAN,
    auto_canceled_by_id BIGINT,
    locked VARCHAR,
    pause_reason VARCHAR,
    source_bridge_id BIGINT,
    failure_reason VARCHAR,
    deb_release VARCHAR,
    INDEX idx_project_id (project_id),
    INDEX idx_ref (ref),
    INDEX idx_status (status),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE ci_builds (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    pipeline_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    when VARCHAR,
    status VARCHAR,
    name VARCHAR,
    stage VARCHAR,
    stage_id BIGINT,
    commit_id BIGINT,
    commands TEXT,
    config_variables JSONB,
    runner_id BIGINT,
    user_id BIGINT,
    type VARCHAR,
    target_url VARCHAR,
    description VARCHAR,
    tag_list TEXT[],
    artifacts_file JSONB,
    artifacts_expire_at TIMESTAMP,
    lock_version INTEGER,
    coverage DECIMAL(5,2),
    coverage_regex VARCHAR,
    auto_canceled_by_id BIGINT,
    upstream_pipeline_id BIGINT,
    INDEX idx_project_id (project_id),
    INDEX idx_pipeline_id (pipeline_id),
    INDEX idx_status (status),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (pipeline_id) REFERENCES ci_pipelines(id) ON DELETE CASCADE
);

CREATE TABLE milestones (
    id BIGINT PRIMARY KEY,
    title VARCHAR NOT NULL,
    description TEXT,
    project_id BIGINT,
    group_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    due_date DATE,
    start_date DATE,
    state VARCHAR DEFAULT 'opened',
    closed_by_id BIGINT,
    closed_at TIMESTAMP,
    iid BIGINT,
    INDEX idx_project_id (project_id),
    INDEX idx_group_id (group_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE labels (
    id BIGINT PRIMARY KEY,
    title VARCHAR NOT NULL,
    color VARCHAR,
    description TEXT,
    project_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    template BOOLEAN DEFAULT FALSE,
    description_html TEXT,
    cached_markdown_version INTEGER,
    type VARCHAR,
    group_id BIGINT,
    INDEX idx_project_id (project_id),
    INDEX idx_group_id (group_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE label_links (
    id BIGINT PRIMARY KEY,
    label_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    target_type VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    INDEX idx_label_id (label_id),
    INDEX idx_target (target_type, target_id),
    FOREIGN KEY (label_id) REFERENCES labels(id) ON DELETE CASCADE
);

CREATE TABLE protected_branches (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    push_access_level INTEGER DEFAULT 40,
    merge_access_level INTEGER DEFAULT 40,
    code_owner_approval_required BOOLEAN DEFAULT FALSE,
    inherited BOOLEAN DEFAULT FALSE,
    INDEX idx_project_id (project_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE deployments (
    id BIGINT PRIMARY KEY,
    iid BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    environment_id BIGINT NOT NULL,
    ref VARCHAR NOT NULL,
    sha VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    user_id BIGINT,
    deployable_id BIGINT,
    deployable_type VARCHAR,
    status VARCHAR DEFAULT 'created',
    finished_at TIMESTAMP,
    INDEX idx_project_id (project_id),
    INDEX idx_environment_id (environment_id),
    INDEX idx_status (status),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE environments (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_url VARCHAR,
    description VARCHAR,
    state VARCHAR DEFAULT 'available',
    kubernetes_namespace VARCHAR,
    stop_action_input JSONB,
    auto_stop_in INTERVAL,
    INDEX idx_project_id (project_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);
