#include <QStringList>
#include <QDebug>

#include "qipgstatement.h"

QiPgStatement::QiPgStatement()
{
}

QString QiPgStatement::driverName(){
    return QStringLiteral("PSQL");
}

QString QiPgStatement::columnTypeName(int type){
    switch (type){
    case QMetaType::Int:
    case QMetaType::UInt:          return QStringLiteral("INTEGER");
    case QMetaType::LongLong:
    case QMetaType::ULongLong:     return QStringLiteral("BIGINT");
    case QMetaType::Float:         return QStringLiteral("REAL");
    case QMetaType::Double:        return QStringLiteral("DOUBLE PRECISION");
    // JSON is stored as TEXT (a serialized string). Postgres won't implicitly cast a
    // bound text parameter into a JSONB column, which breaks parameterized inserts —
    // and Qivot never queries into JSON, so TEXT is the portable, correct choice.
    case QMetaType::QString:
    case QMetaType::QStringList:
    case QMetaType::QJsonObject:
    case QMetaType::QJsonArray:
    case QMetaType::QVariantMap:
    case QMetaType::QVariantList:  return QStringLiteral("TEXT");
    case QMetaType::QDateTime:     return QStringLiteral("TIMESTAMP");
    case QMetaType::QDate:         return QStringLiteral("DATE");
    case QMetaType::QTime:         return QStringLiteral("TIME");
    case QMetaType::QByteArray:    return QStringLiteral("BYTEA");
    case QMetaType::Bool:          return QStringLiteral("BOOLEAN");
    default: break;
    }
#if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
    if (QMetaType(type).flags() & QMetaType::IsEnumeration) return QStringLiteral("INTEGER");
#else
    if (QMetaType::typeFlags(static_cast<QMetaType::Type>(type)) & QMetaType::IsEnumeration) return QStringLiteral("INTEGER");
#endif
    return QString();
}

QString QiPgStatement::primaryKeyClause(const QString &typeName){
    // An auto-incrementing integer key uses an identity column in modern Postgres.
    if (typeName == QLatin1String("INTEGER") || typeName == QLatin1String("BIGINT"))
        return QStringLiteral("PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY");
    return QStringLiteral("PRIMARY KEY");
}

QString QiPgStatement::replaceInto(QiModelMetaInfo *info, QStringList fields){
    // "REPLACE INTO" (insert, or overwrite the row on a primary-key clash) is a
    // SQLite/MySQL idiom Postgres doesn't have. Its exact equivalent is an upsert
    // whose conflict target is the primary key.
    QString pk = info->primaryKeyName();
    if (pk.isEmpty()) pk = QStringLiteral("id");
    return upsertInto(info, fields, QStringList() << pk);
}

QString QiPgStatement::lastInsertIdQuery() const {
    // QPSQL's lastInsertId() returns the row OID, not the serial/identity id — and putting
    // RETURNING into the prepared INSERT is unreliable with QPSQL. So after a normal insert we
    // ask Postgres for the last generated sequence value in this session.
    return QStringLiteral("SELECT lastval()");
}

QStringList QiPgStatement::createFtsIndex(const QiBaseFtsIndex &index){
    Q_UNUSED(index);
    qWarning() << "QiPgStatement: full-text search (FTS) is not supported on Postgres yet; skipping.";
    return QStringList();
}

QStringList QiPgStatement::dropFtsIndex(QString name){
    Q_UNUSED(name);
    return QStringList();
}
