#include <QStringList>
#include <QDebug>

#include "qipgstatement.h"

QiPgStatement::QiPgStatement()
{
}

QString QiPgStatement::driverName(){
    return QStringLiteral("PSQL");
}

QString QiPgStatement::columnTypeName(int type){
    switch (type){
    case QMetaType::Int:
    case QMetaType::UInt:          return QStringLiteral("INTEGER");
    case QMetaType::LongLong:
    case QMetaType::ULongLong:     return QStringLiteral("BIGINT");
    case QMetaType::Float:         return QStringLiteral("REAL");
    case QMetaType::Double:        return QStringLiteral("DOUBLE PRECISION");
    case QMetaType::QJsonObject:
    case QMetaType::QJsonArray:    return QStringLiteral("JSONB");     // native binary JSON
    case QMetaType::QString:
    case QMetaType::QStringList:
    case QMetaType::QVariantMap:
    case QMetaType::QVariantList:  return QStringLiteral("TEXT");
    case QMetaType::QDateTime:     return QStringLiteral("TIMESTAMP");
    case QMetaType::QDate:         return QStringLiteral("DATE");
    case QMetaType::QTime:         return QStringLiteral("TIME");
    case QMetaType::QByteArray:    return QStringLiteral("BYTEA");
    case QMetaType::Bool:          return QStringLiteral("BOOLEAN");
    default: break;
    }
#if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
    if (QMetaType(type).flags() & QMetaType::IsEnumeration) return QStringLiteral("INTEGER");
#else
    if (QMetaType::typeFlags(static_cast<QMetaType::Type>(type)) & QMetaType::IsEnumeration) return QStringLiteral("INTEGER");
#endif
    return QString();
}

QString QiPgStatement::primaryKeyClause(const QString &typeName){
    // An auto-incrementing integer key uses an identity column in modern Postgres.
    if (typeName == QLatin1String("INTEGER") || typeName == QLatin1String("BIGINT"))
        return QStringLiteral("PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY");
    return QStringLiteral("PRIMARY KEY");
}

QString QiPgStatement::_insertInto(QiModelMetaInfo *info, QString type, QStringList fields){
    // Postgres has no lastInsertId(); ask for the new id back on the same round-trip.
    QString sql = QiSqlStatement::_insertInto(info, type, fields);
    if (sql.endsWith(QLatin1Char(';')))
        sql.chop(1);
    sql += QStringLiteral(" RETURNING id;");
    return sql;
}

QStringList QiPgStatement::createFtsIndex(const QiBaseFtsIndex &index){
    Q_UNUSED(index);
    qWarning() << "QiPgStatement: full-text search (FTS) is not supported on Postgres yet; skipping.";
    return QStringList();
}

QStringList QiPgStatement::dropFtsIndex(QString name){
    Q_UNUSED(name);
    return QStringList();
}
